// SmartReorderPanel.tsx — AI-powered "Restock My Store" drawer
import React, { useEffect, useMemo, useState } from "react";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Trash2, Sparkles, Clock, Boxes, Loader2, CheckCircle2 } from "lucide-react";
import retailerAnalyticsService, { ReorderSuggestion } from "@/services/retailerAnalyticsService";
import { toast } from "sonner";

interface Props {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  retailerId: string;
  onSubmitted?: () => void;
}

const URG_TONE: Record<string, string> = {
  critical: "bg-rose-100 text-rose-700",
  warning: "bg-amber-100 text-amber-700",
  healthy: "bg-emerald-100 text-emerald-700",
};

export default function SmartReorderPanel({ open, onOpenChange, retailerId, onSubmitted }: Props) {
  const [items, setItems] = useState<(ReorderSuggestion & { included: boolean; qty: number })[]>([]);
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (!open) return;
    setLoading(true);
    retailerAnalyticsService
      .reorderSuggestions(retailerId)
      .then(({ data }) =>
        setItems(
          data.map((s) => ({ ...s, included: true, qty: s.recommended_quantity }))
        )
      )
      .finally(() => setLoading(false));
  }, [open, retailerId]);

  const totalUnits = useMemo(
    () => items.filter((i) => i.included).reduce((a, b) => a + (Number(b.qty) || 0), 0),
    [items]
  );
  const totalSkus = items.filter((i) => i.included).length;

  const submit = async () => {
    const payload = items
      .filter((i) => i.included && Number(i.qty) > 0)
      .map((i) => ({ product_id: i.product_id, quantity: Number(i.qty) }));
    if (!payload.length) {
      toast.error("Add at least one item to reorder.");
      return;
    }
    setSubmitting(true);
    const res = await retailerAnalyticsService.submitReorder(retailerId, {
      items: payload,
      note: "Smart reorder — generated by AI assistant",
    });
    setSubmitting(false);
    if (res.queued) {
      toast.success("Saved offline — will sync when you're back online.");
    } else {
      toast.success(`Reorder submitted to your distributor (${payload.length} item${payload.length === 1 ? "" : "s"}).`);
    }
    onOpenChange(false);
    onSubmitted && onSubmitted();
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent
        side="right"
        className="w-full sm:max-w-lg p-0 flex flex-col"
        data-testid="smart-reorder-panel"
      >
        <SheetHeader className="px-5 pt-5 pb-3 border-b">
          <div className="flex items-center gap-2">
            <div className="h-9 w-9 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center shadow-sm">
              <Sparkles className="h-4 w-4 text-white" />
            </div>
            <div>
              <SheetTitle className="text-left text-base">Smart Reorder</SheetTitle>
              <SheetDescription className="text-left text-xs">
                AI suggestions based on your sales velocity & current stock.
              </SheetDescription>
            </div>
          </div>
        </SheetHeader>

        <div className="flex-1 overflow-y-auto">
          {loading && (
            <div className="p-8 text-center text-slate-500 text-sm flex flex-col items-center gap-2">
              <Loader2 className="h-5 w-5 animate-spin" />
              Analyzing your inventory…
            </div>
          )}
          {!loading && items.length === 0 && (
            <div className="p-8 text-center" data-testid="reorder-empty">
              <CheckCircle2 className="h-10 w-10 text-emerald-500 mx-auto mb-3" />
              <div className="font-semibold text-slate-900">All stocked up</div>
              <div className="text-sm text-slate-500 mt-1">
                No items below threshold right now. The AI will alert you when reorder is needed.
              </div>
            </div>
          )}
          {!loading && items.length > 0 && (
            <ul className="divide-y divide-slate-100">
              {items.map((it) => (
                <li
                  key={it.product_id}
                  className={`px-4 py-3 ${it.included ? "" : "opacity-50"}`}
                  data-testid={`reorder-row-${it.product_id}`}
                >
                  <div className="flex items-start gap-3">
                    <input
                      type="checkbox"
                      checked={it.included}
                      onChange={(e) =>
                        setItems((arr) =>
                          arr.map((x) => (x.product_id === it.product_id ? { ...x, included: e.target.checked } : x))
                        )
                      }
                      className="mt-1 h-4 w-4 rounded border-slate-300"
                      data-testid={`reorder-toggle-${it.product_id}`}
                    />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-2">
                        <div className="font-medium text-slate-900 text-[14px] truncate">{it.product?.name}</div>
                        <span
                          className={`text-[10px] font-semibold uppercase tracking-wider rounded-full px-2 py-0.5 ${URG_TONE[it.urgency]}`}
                        >
                          {it.urgency}
                        </span>
                      </div>
                      <div className="flex flex-wrap gap-3 text-[12px] text-slate-500 mt-1">
                        <span className="inline-flex items-center gap-1">
                          <Boxes className="h-3 w-3" /> Stock: <b className="text-slate-700">{it.current_quantity}</b>
                        </span>
                        <span className="inline-flex items-center gap-1">
                          <Clock className="h-3 w-3" />
                          {it.days_remaining < 999 ? <>~<b className="text-slate-700">{it.days_remaining}</b> days left</> : <>Slow seller</>}
                        </span>
                        <span>{it.velocity.toFixed(1)} u/day</span>
                      </div>
                      <div className="flex items-center gap-3 mt-2.5">
                        <label className="text-[11px] text-slate-500 uppercase tracking-wider font-medium">
                          Order qty
                        </label>
                        <Input
                          type="number"
                          min={0}
                          value={it.qty}
                          onChange={(e) =>
                            setItems((arr) =>
                              arr.map((x) =>
                                x.product_id === it.product_id ? { ...x, qty: Number(e.target.value || 0) } : x
                              )
                            )
                          }
                          className="h-9 w-24"
                          data-testid={`reorder-qty-${it.product_id}`}
                        />
                        <button
                          onClick={() => setItems((arr) => arr.filter((x) => x.product_id !== it.product_id))}
                          className="text-slate-400 hover:text-rose-600 transition-colors p-1"
                          data-testid={`reorder-remove-${it.product_id}`}
                          aria-label="Remove"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          )}
        </div>

        <SheetFooter className="border-t px-5 py-3 bg-slate-50/50 flex-col gap-3 sm:flex-col">
          <div className="flex items-center justify-between text-[12px] text-slate-600 w-full">
            <span>{totalSkus} item{totalSkus === 1 ? "" : "s"}</span>
            <span>
              <b className="text-slate-900">{totalUnits}</b> total units
            </span>
          </div>
          <Button
            onClick={submit}
            disabled={submitting || totalSkus === 0}
            className="w-full h-12 bg-slate-900 hover:bg-slate-800 text-base"
            data-testid="reorder-submit"
          >
            {submitting ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Sparkles className="h-4 w-4 mr-2" />}
            Send reorder to distributor
          </Button>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  );
}
